/*
 Navicat Premium Data Transfer

 Source Server         : 38.34.244.41_3306
 Source Server Type    : MariaDB
 Source Server Version : 50568 (5.5.68-MariaDB)
 Source Host           : 38.34.244.41:3306
 Source Schema         : keyman

 Target Server Type    : MariaDB
 Target Server Version : 50568 (5.5.68-MariaDB)
 File Encoding         : 65001

 Date: 03/05/2023 16:39:23
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for proenwords
-- ----------------------------
DROP TABLE IF EXISTS `proenwords`;
CREATE TABLE `proenwords`  (
  `id` int(255) UNSIGNED NOT NULL AUTO_INCREMENT,
  `short_words` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `long_words` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `trans_cn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `supporter` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '无名氏',
  `type` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 994 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of proenwords
-- ----------------------------
INSERT INTO `proenwords` VALUES (1, NULL, 'Absolute', '绝对的', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (2, NULL, 'Activate', '激活', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (3, NULL, 'Alpha', '透明度', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (4, NULL, 'Arrow', '箭头', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (5, NULL, 'Access', '访问', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (6, NULL, 'Access Function', '访问 函数', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (7, NULL, 'Accumulator', '累加器', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (8, NULL, 'Adapter', '适配器', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (9, NULL, 'Address', '地址', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (10, NULL, 'Algorithm', '算法', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (11, NULL, 'Algebraic Data Type', '代数 数据 类型', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (12, NULL, 'Allocate', '分配', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (13, NULL, 'Alternative', '备选', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (14, NULL, 'Anaphoric', '指代', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (15, NULL, 'Annotation', '注解', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (16, NULL, 'Antecedent', '前提', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (17, NULL, 'Append', '追加', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (18, NULL, 'Applicative', '应用序', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (19, NULL, 'Argument', '参数', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (20, NULL, 'Array', '数组', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (21, NULL, 'Assembly', '汇编', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (22, NULL, 'Assignment', '赋值', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (23, NULL, 'Attribute', '属性', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (24, NULL, 'Augmented', '扩充', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (25, NULL, 'Backquote', '反引用', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (26, NULL, 'Backward Compatible', '向下 兼容', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (27, NULL, 'Binding', '绑定', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (28, NULL, 'Binding Vector', '绑定 向量', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (29, NULL, 'Block', '块', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (30, NULL, 'Block Structure', '块 结构', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (31, NULL, 'Boilerplate', '公式化', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (32, NULL, 'Branch', '分支', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (33, NULL, 'Breakpoint', '断点', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (34, NULL, 'Buffer', '缓冲区', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (35, NULL, 'Building', '创建', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (36, NULL, 'Byte', '字节', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (37, NULL, 'Call', '调用', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (38, NULL, 'Callback', '回调', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (39, NULL, 'Capture', '捕捉', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (40, NULL, 'Case', '分支', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (41, NULL, 'Character', '字符', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (42, NULL, 'Circular Definition', '循环 定义', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (43, NULL, 'Class', '类', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (44, NULL, 'Class Declaration', '类 声明', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (45, NULL, 'Class Library', '类 库', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (46, NULL, 'Column', '行', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (47, NULL, 'Compile', '编译', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (48, NULL, 'Compile Time', '编译 期', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (49, NULL, 'Compiler', '编译器', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (50, NULL, 'Compound Value', '复合 数据', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (51, NULL, 'Conditional Variable', '条件 变量', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (52, NULL, 'Configuration', '配置', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (53, NULL, 'Connection', '连接', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (54, NULL, 'Constant', '常量', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (55, NULL, 'Copy', '拷贝', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (56, NULL, 'Create', '创建', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (57, NULL, 'Data', '数据', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (58, NULL, 'Data Structure', '数据 结构', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (59, NULL, 'Data Type', '数据 类型', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (60, NULL, 'Database', '数据库', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (61, NULL, 'Database Schema', '数据库 模式', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (62, NULL, 'Debugging', '调试', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (63, NULL, 'Declaration', '声明', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (64, NULL, 'Define', '定义', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (65, NULL, 'Defer', '推迟', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (66, NULL, 'Directory', '目录', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (67, NULL, 'Effect', '效果', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (68, NULL, 'Embedded Language', '嵌入式 语句', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (69, NULL, 'Equal', '相等', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (70, NULL, 'Equation', '方程', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (71, NULL, 'Evaluate', '求值', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (72, NULL, 'Event', '事件', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (73, NULL, 'Extent', '范围', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (74, NULL, 'Field', '字段', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (75, NULL, 'File', '文件', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (76, NULL, 'Flush', '刷新', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (77, NULL, 'Font', '字体', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (78, NULL, 'Form', '表单', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (79, NULL, 'Framework', '框架', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (80, NULL, 'Function', '函数', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (81, NULL, 'Function Object', '函数 对象', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (82, NULL, 'Functionality', '功能性', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (83, NULL, 'Generate', '生成', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (84, NULL, 'Global', '全局', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (85, NULL, 'Global Declaration', '全局 声明', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (86, NULL, 'Hack', '破解', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (87, NULL, 'Handle', '处理器', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (88, NULL, 'Head', '头部', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (89, NULL, 'Hypertext Markup Language', '超文本 标记 语言', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (90, NULL, 'Import', '导入', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (91, NULL, 'Link', '链接', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (92, NULL, 'List', '列表', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (93, NULL, 'Local', '局部的', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (94, NULL, 'Loop', '循环', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (95, NULL, 'Native', '本地的', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (96, NULL, 'Online', '在线', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (97, NULL, 'Overflow', '溢出', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (98, NULL, 'Parse', '解析', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (99, NULL, 'Query', '查询', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (100, NULL, 'Quote', '引用', '黄水懿', 'B');
INSERT INTO `proenwords` VALUES (101, NULL, 'Compile', '编绎', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (102, NULL, 'Run', '运行', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (103, NULL, 'Class', '类', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (104, NULL, 'Object', '对象', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (105, NULL, 'System', '系统', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (106, NULL, 'Runtime', '运行时', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (107, NULL, 'Print', '打印', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (108, NULL, 'Line', '行', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (109, NULL, 'Variable', '变量', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (110, NULL, 'Type', '类型', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (111, NULL, 'Static', '静态的', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (112, NULL, 'Array', '数组', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (113, NULL, 'Parameter', '参数', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (114, NULL, 'Method', '方法', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (115, NULL, 'Function', '函数', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (116, NULL, 'Public', '公有的', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (117, NULL, 'Default', '默认', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (118, NULL, 'Get', '得到', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (119, NULL, 'Private', '私有的', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (120, NULL, 'Import', '导入', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (121, NULL, 'Set', '设置', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (122, NULL, 'Package', '包', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (123, NULL, 'Access', '访问', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (124, NULL, 'Protected', '受保护的', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (125, NULL, 'Void', '无', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (126, NULL, 'Operation', '操作运算', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (127, NULL, 'Member-Variable', '成员变量', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (128, NULL, 'Member-Function', '成员函数', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (129, NULL, 'Extends', '继承', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (130, NULL, 'Interface', '接口', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (131, NULL, 'Overload', '重载', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (132, NULL, 'Implements', '实现', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (133, NULL, 'Exception', '异常', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (134, NULL, 'Override', '重写覆盖', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (135, NULL, 'Final', '不能改变的', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (136, NULL, 'Main', '主要的', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (137, NULL, 'Void', '无返回', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (138, NULL, 'Double', '双精度浮点数', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (139, NULL, 'String', '字符串', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (140, NULL, 'Character', '字符', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (141, NULL, 'Integer', '整数', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (142, NULL, 'Boolean', '布尔', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (143, NULL, 'True', '真', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (144, NULL, 'False', '假', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (145, NULL, 'If', '如果', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (146, NULL, 'Else', '否则', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (147, NULL, 'Case', '案列', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (148, NULL, 'Default', '默认', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (149, NULL, 'Switch', '开关', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (150, NULL, 'Break', '中断', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (151, NULL, 'While', '循环', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (152, NULL, 'Do', '执行', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (153, NULL, 'Index', '索引', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (154, NULL, 'Bug', '错误', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (155, NULL, 'Debug', '调试', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (156, NULL, 'Step', '步骤', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (157, NULL, 'Point', '点', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (158, NULL, 'Continue', '继续', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (159, NULL, 'Return', '返回', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (160, NULL, 'Type', '类型', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (161, NULL, 'Info', '信息', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (162, NULL, 'Primitive', '原型', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (163, NULL, 'Reference', '引用', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (164, NULL, 'Length', '长度', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (165, NULL, 'Target', '目标', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (166, NULL, 'Hidden', '隐藏', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (167, NULL, 'Radio', '单选', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (168, NULL, 'Blank', '空白', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (169, NULL, 'Style', '样式', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (170, NULL, 'Insert', '插入', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (171, NULL, 'Compare', '比较', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (172, NULL, 'Null', '空', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (173, NULL, 'Initial', '初始化', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (174, NULL, 'Parameter', '参数', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (175, NULL, 'Since', '因为', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (176, NULL, 'Version', '版本', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (177, NULL, 'Orient', '导向', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (178, NULL, 'Document', '文件', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (179, NULL, 'Display', '显示', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (180, NULL, 'Method', '方法', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (181, NULL, 'Shape', '形状', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (182, NULL, 'Operator', '操作符', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (183, NULL, 'Protect', '保护', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (184, NULL, 'Private', '私有的', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (185, NULL, 'Search', '搜索', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (186, NULL, 'Upper', '大写', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (187, NULL, 'Count', '计数', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (188, NULL, 'List', '列表', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (189, NULL, 'Equal', '相等', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (190, NULL, 'Lower', '降低', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (191, NULL, 'Last', '最后', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (192, NULL, 'Mini', '最小', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (193, NULL, 'Max', '最大', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (194, NULL, 'Concatenate', '链接', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (195, NULL, 'Delete', '删除', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (196, NULL, 'Head', '头', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (197, NULL, 'Title', '标题', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (198, NULL, 'Body', '正文', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (199, NULL, 'Input', '输入', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (200, NULL, 'Onclick', '点击', '关钰荣', 'B');
INSERT INTO `proenwords` VALUES (201, NULL, 'Forms', '窗体', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (202, NULL, 'Partial', '部分', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (203, NULL, 'Event', '事件', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (204, NULL, 'Messgas', '信息', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (205, NULL, 'Icon', '图示', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (206, NULL, 'Label', '标签', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (207, NULL, 'Combo', '组合', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (208, NULL, 'Anchor', '抛锚', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (209, NULL, 'Dock', '码头', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (210, NULL, 'Application', '软件', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (211, NULL, 'Exit', '退出', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (212, NULL, 'Menu', '菜单', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (213, NULL, 'Tool', '工具', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (214, NULL, 'Strip', '剥去', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (215, NULL, 'Image', '图片', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (216, NULL, 'List', '名单', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (217, NULL, 'View', '查看', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (218, NULL, 'Detail', '细节', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (219, NULL, 'Range', '范围', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (220, NULL, 'Break', '中断', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (221, NULL, 'Continue', '继续', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (222, NULL, 'Switch', '开关', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (223, NULL, 'Array', '数组', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (224, NULL, 'Each', '每个', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (225, NULL, 'While', '循环', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (226, NULL, 'Context', '上下文', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (227, NULL, 'Gender', '性别', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (228, NULL, 'Framework', '框架', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (229, NULL, 'Common', '共同特点', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (230, NULL, 'Language', '语言', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (231, NULL, 'Runtime', '运行时间', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (232, NULL, 'Intermediate', '中间体', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (233, NULL, 'System', '系统', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (234, NULL, 'Type', '类型', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (235, NULL, 'Structure', '结构', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (236, NULL, 'Encapsulation', '封装', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (237, NULL, 'Stack', '栈', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (238, NULL, 'Constructor', '构造函数', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (239, NULL, 'Overload', '过载', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (240, NULL, 'Collection', '集合', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (241, NULL, 'General', '通用的', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (242, NULL, 'Virtual', '虚拟', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (243, NULL, 'Override', '覆盖', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (244, NULL, 'Protected', '保护', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (245, NULL, 'Merit', '优点', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (246, NULL, 'Turn', '转', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (247, NULL, 'Inheritance', '继承', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (248, NULL, 'Substitution', '替代', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (249, NULL, 'Principle', '原则', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (250, NULL, 'Speed', '速度', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (251, NULL, 'Unique', '独一无二的', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (252, NULL, 'Design', '设计', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (253, NULL, 'Program', '程序', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (254, NULL, 'Extensible', '可扩展的', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (255, NULL, 'Markup', '标记', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (256, NULL, 'Node', '节点', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (257, NULL, 'Serialize', '序列化', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (258, NULL, 'Attribute', '属性', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (259, NULL, 'File', '文件', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (260, NULL, 'Directory', '目录', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (261, NULL, 'Binary', '二进制', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (262, NULL, 'Data', '数据', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (263, NULL, 'Set', '设置', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (264, NULL, 'Fill', '填充', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (265, NULL, 'Grid', '网格', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (266, NULL, 'Grade', '等级', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (267, NULL, 'Check', '检查', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (268, NULL, 'Active', '活动', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (269, NULL, 'Object', '对象', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (270, NULL, 'Connection', '连接', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (271, NULL, 'Command', '命令', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (272, NULL, 'Execute', '执行', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (273, NULL, 'Query', '查询', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (274, NULL, 'Segment Fault', '段 错误', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (275, NULL, 'Linker', '链接器', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (276, NULL, 'Debugging', '调试', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (277, 'printf', 'Print Format', '格式化 打印', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (278, NULL, 'GNU Compiler Collection', '编译器 套件', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (279, NULL, 'International Organization For Standardization', '国际 标准化 组织', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (280, NULL, 'Undefined', '未定义', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (281, NULL, 'Defined Function', '自定义 函数', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (282, NULL, 'Factorial', '阶乘', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (283, NULL, 'Redefinition', '重复定义', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (284, NULL, 'Index', '下标', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (285, 'LF', 'Line Feed', '换行', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (286, NULL, 'String', '字符串', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (287, NULL, 'String Name', '是字符串的名字或是字符数组的名字', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (288, NULL, 'Off Normal Lower', '下限 越界', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (289, NULL, 'Off Normal Upper', '上限 越界', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (290, NULL, 'Variable Length Array', '变 长 数组', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (291, NULL, 'Null', '空', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (292, 'Nl', 'Newline', '换行', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (293, NULL, 'Global Variable', '全局 变量', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (294, NULL, 'Temp', '临时', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (295, NULL, 'Temporary', '暂时的', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (296, NULL, 'Core', '核心', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (297, NULL, 'Control Unit', '控制中心', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (298, NULL, 'Open Graphics Library', '开放 图形 库', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (299, NULL, 'Remote Debugger', '远程 调试器', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (300, NULL, 'Constant', '常量', '黎恒光', 'B');
INSERT INTO `proenwords` VALUES (301, NULL, 'Generator', '产生器，生产者', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (302, NULL, 'Driver Module', '驱动模块', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (303, NULL, 'Mathematician', '专家', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (304, NULL, 'Line By Line', '逐行', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (305, NULL, 'Operator', '作符', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (306, NULL, 'Translate', '翻译，解释', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (307, NULL, 'Modular', '摸块化', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (308, NULL, 'Cumbersome', '讨厌的，麻烦的', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (309, NULL, 'Teaching Programming', '编程教学', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (310, NULL, 'Lengthy', '冗长的，漫长的', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (311, NULL, 'Alter', '改变', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (312, NULL, 'Flaw', '缺点裂纹', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (313, NULL, 'Devclop', '发达', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (314, NULL, 'Separate', '各别的', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (315, NULL, 'Recompile', '编译', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (316, NULL, 'Assist', '帮助', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (317, NULL, 'Cycle', '循环', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (318, NULL, 'Technician', '技师', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (319, NULL, 'Remove', '移动，除去', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (320, NULL, 'Straight Line', '直线', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (321, NULL, 'Category', '种类，类项', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (322, NULL, 'Rectangle', '长方形，矩形', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (323, NULL, 'Register', '寄存器', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (324, NULL, 'By Convention', '按照惯例', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (325, NULL, 'Cyptic', '含义模糊的', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (326, NULL, 'Diamond-Shaped', '菱形的', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (327, NULL, 'Bracket', '括号', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (328, NULL, 'Decision', '判断', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (329, NULL, 'Obviate', '除去，排除', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (330, NULL, 'Terminal', '终端', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (331, NULL, 'Keyword', '关键', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (332, NULL, 'Card Reader', '阅读器', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (333, NULL, 'Worder Module', '工作模块', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (334, NULL, 'Archaic', '己废的，古老的', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (335, NULL, 'Main Module', '主模块', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (336, NULL, 'Sufficient', '充分的，足够的', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (337, NULL, 'Submodule', '子模块', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (338, NULL, 'Data Processing', '数据处理', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (339, NULL, 'Modify', '修正，修改', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (340, NULL, 'Business Application', '商业应用', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (341, NULL, 'Outline', '轮廓，概要', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (342, NULL, 'Scientific Application', '科学应用', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (343, NULL, 'Compose', '分解', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (344, NULL, 'Lexical', '字典的，词汇', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (345, NULL, 'Code', '代码', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (346, NULL, 'Non-Programmer', '非编程人员', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (347, NULL, 'Node', '节点', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (348, NULL, 'Notation', '记号法，表示法，注释', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (349, NULL, 'Pseudocode', '伪代码', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (350, NULL, 'Verbosity', '唠叨，冗长', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (351, NULL, 'Commas', '逗点逗号', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (352, NULL, 'Record', '记录', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (353, NULL, 'Documentation', '文档', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (354, NULL, 'Subrecord', '子记录', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (355, NULL, 'Flowchart Flow', '程表流程', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (356, NULL, 'Data Division', '数据部', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (357, NULL, 'Visual', '视觉的', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (358, NULL, 'Procedure Division', '过程部', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (359, NULL, 'Represent', '表现，表示，代表', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (360, NULL, 'Comprise', '包含,构成', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (361, NULL, 'Structured Techniques', '结构化技术', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (362, NULL, 'Operator', '运算符，算子', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (363, NULL, 'Straightforward', '笔直的，率直的', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (364, NULL, 'Commercial Package', '商业软件包', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (365, NULL, 'Subroutine', '子程序', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (366, NULL, 'Program Design', '程序设计', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (367, NULL, 'Writing Program', '编写程序', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (368, NULL, 'Standardize', '使标准化', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (369, NULL, 'Coding The Program', '编程', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (370, NULL, 'Simplify', '单一化，简单化', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (371, NULL, 'Programming', '程序', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (372, NULL, 'Revision', '校订', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (373, NULL, 'Programmer', '程序员', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (374, NULL, 'Occupy', '占领，住进', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (375, NULL, 'Logic', '逻辑，逻辑学', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (376, NULL, 'BASIC', '初学者通用符号指令代码', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (377, NULL, 'Machine Code', '机器代码', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (378, NULL, 'Teaching Language', '教学语言', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (379, NULL, 'Debug', '调试', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (380, NULL, 'Compactness', '紧凑的，紧密的', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (381, NULL, 'Timesharing System', '分时系统', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (382, NULL, 'Description', '描述，说明', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (383, NULL, 'Interactive Language', '交互式语言', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (384, NULL, 'Break', '中断', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (385, NULL, 'Manufacturer', '制造业者', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (386, NULL, 'Structure Chart', '结构图', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (387, NULL, 'Dialect', '方言，语调', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (388, NULL, 'Program Flow', '程序流', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (389, NULL, 'Expense', '费用，代价', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (390, NULL, 'Manager Module', '管理模块', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (391, NULL, 'Uniformity', '同样，划一', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (392, NULL, 'Structure', '结构', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (393, NULL, 'Member', '成员', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (394, NULL, 'Tag', '标记', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (395, NULL, 'Function', '函数', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (396, NULL, 'Enumerate', '枚举', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (397, NULL, 'Union', '联合', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (398, NULL, 'Create', '创建', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (399, NULL, 'Delete', '删除', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (400, NULL, 'Modify', '修改', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (401, NULL, 'Insert', '插入', '吴振宇', 'B');
INSERT INTO `proenwords` VALUES (402, 'CPU', 'Center Processor Unit', '中央处理单元', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (403, NULL, 'Mainboard', '主板', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (404, NULL, 'Hard Disk', '硬盘', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (405, NULL, 'Cd-Rom', '光盘驱动器（光驱）', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (406, NULL, 'Monitor', '监视器', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (407, NULL, 'Keyboard', '键盘', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (408, NULL, 'Mouse', '鼠标', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (409, NULL, 'Chip', '芯片', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (410, NULL, 'Cd-R', '光盘刻录机', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (411, NULL, 'Hub', '集线器', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (412, NULL, 'Modem Modulator Demodulator', '调制解调器', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (413, 'P-P', 'Plug And Play', '即插即用', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (414, 'UPS', 'Uninterruptable Power Supply', '不间断电源', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (415, 'BIOS', 'Basic Input Output System', '基本输入输出系统', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (416, 'COMS', 'Complementary Metal Oxide Semiconductor', '互补金属氧化物半导体', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (417, NULL, 'Setup', '安装', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (418, NULL, 'Uninstall', '卸载', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (419, NULL, 'Wizard', '向导', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (420, 'OS', 'Operation Systrem', '操作系统', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (421, 'OA', 'Office Automation', '办公自动化', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (422, NULL, 'Exit', '退出', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (423, NULL, 'Edit', '编辑', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (424, NULL, 'Copy', '复制', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (425, NULL, 'Cut', '剪切', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (426, NULL, 'Paste', '粘贴', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (427, NULL, 'Delete', '删除', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (428, NULL, 'Select', '选择', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (429, NULL, 'Find', '查找', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (430, NULL, 'Select All', '全选', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (431, NULL, 'Replace', '替换', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (432, NULL, 'Undo', '撤消', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (433, NULL, 'Redo', '重做', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (434, NULL, 'Program', '程序', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (435, NULL, 'License', '许可证', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (436, NULL, 'Back', '前一步', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (437, NULL, 'Next', '下一步', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (438, NULL, 'Finish', '结束', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (439, NULL, 'Folder', '文件夹', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (440, NULL, 'Destination Folder', '目的文件夹', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (441, NULL, 'User', '用户', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (442, NULL, 'Click', '点击', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (443, NULL, 'Double Click', '双击', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (444, NULL, 'Right Click', '右击', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (445, NULL, 'Settings', '设置', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (446, NULL, 'Update', '更新', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (447, NULL, 'Release', '发布', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (448, NULL, 'Data', '数据', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (449, NULL, 'Data Base', '数据库', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (450, 'DBMS', 'Data Base Manege System', '数据库管理系统', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (451, NULL, 'View', '视图', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (452, NULL, 'Insert', '插入', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (453, NULL, 'Object', '对象', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (454, NULL, 'Configuration', '配置', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (455, NULL, 'Command', '命令', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (456, NULL, 'Document', '文档', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (457, 'POST', 'Power On Self Test', '电源自检程序', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (458, NULL, 'Cursor', '光标', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (459, NULL, 'Attribute', '属性', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (460, NULL, 'Icon', '图标', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (461, NULL, 'Service Pack', '服务补丁', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (462, NULL, 'Option Pack', '功能补丁', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (463, NULL, 'Demo', '演示', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (464, NULL, 'Short Cut', '快捷方式', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (465, NULL, 'Exception', '异常', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (466, NULL, 'Debug', '调试', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (467, NULL, 'Previous', '前一个', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (468, NULL, 'Column', '行', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (469, NULL, 'Row', '列', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (470, NULL, 'Restart', '重新启动', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (471, NULL, 'Text', '文本', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (472, NULL, 'Font', '字体', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (473, NULL, 'Size', '大小', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (474, NULL, 'Scale', '比例', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (475, NULL, 'Interface', '界面', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (476, NULL, 'Function', '函数', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (477, NULL, 'Access', '访问', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (478, NULL, 'Manual', '指南', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (479, NULL, 'Active', '激活', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (480, NULL, 'Computer Language', '计算机语言', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (481, NULL, 'Menu', '菜单', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (482, 'GUI', 'Graphical User Interfaces', '图形用户界面', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (483, NULL, 'Template', '模版', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (484, NULL, 'Page Setup', '页面设置', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (485, NULL, 'Password', '口令', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (486, NULL, 'Code', '密码', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (487, NULL, 'Print Preview', '打印预览', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (488, NULL, 'Zoom In', '放大', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (489, NULL, 'Zoom Out', '缩小', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (490, NULL, 'Pan', '漫游', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (491, NULL, 'Cruise', '漫游', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (492, NULL, 'Full Screen', '全屏', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (493, NULL, 'Tool Bar', '工具条', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (494, NULL, 'Status Bar', '状态条', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (495, NULL, 'Ruler', '标尺', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (496, NULL, 'Table', '表', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (497, NULL, 'Paragraph', '段落', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (498, NULL, 'Symbol', '符号', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (499, NULL, 'Style', '样式', '卢贤煜', 'B');
INSERT INTO `proenwords` VALUES (500, NULL, 'Command', '命令', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (501, NULL, 'Program', '程序', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (502, NULL, 'Line', '数据', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (503, NULL, 'List', '列表', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (504, NULL, 'Directory', '目录', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (505, NULL, 'Character', '字符', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (506, NULL, 'Record', '记录', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (507, NULL, 'Database', '数据库', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (508, NULL, 'Memory', '存储器', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (509, NULL, 'Information', '信息', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (510, NULL, 'Group', '组', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (511, NULL, 'Field', '字段', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (512, NULL, 'Procedure', '过程', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (513, NULL, 'Example', '例子', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (514, NULL, 'Create', '建立', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (515, NULL, 'Edit', '编辑', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (516, NULL, 'Parameter', '参数', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (517, NULL, 'Variable', '变量', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (518, NULL, 'String', '字符串', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (519, NULL, 'Active', '激活', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (520, NULL, 'Function', '函数', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (521, NULL, 'Selection', '选择', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (522, NULL, 'Value', '值', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (523, NULL, 'Save', '保存', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (524, NULL, 'Control', '控制，管理', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (525, NULL, 'System', '系统', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (526, NULL, 'Data', '数据', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (527, NULL, 'Setting', '设置', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (528, NULL, 'View', '视图', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (529, NULL, 'Path', '路径', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (530, NULL, 'Operation', '操作', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (531, NULL, 'Filename', '文件名', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (532, NULL, 'Execute', '实行', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (533, NULL, 'Error', '错误', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (534, NULL, 'Run', '运行', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (535, NULL, 'Statement', '语句', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (536, NULL, 'Store', '存储器', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (537, NULL, 'Decimal', '十进制', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (538, NULL, 'Define', '分辨', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (539, NULL, 'Attribute', '属性', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (540, NULL, 'Dos', '磁盘操作系统', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (541, NULL, 'Modify', '修改', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (542, NULL, 'Array', '数组', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (543, NULL, 'Editor', '编辑程序', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (544, NULL, 'Backup', '备份', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (545, NULL, 'Subset', '子集', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (546, NULL, 'Code', '代码', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (547, NULL, 'Rename', '更名，改名', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (548, NULL, 'Combination', '结合', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (549, NULL, 'Section', '节，段', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (550, NULL, 'Access', '选取，存取', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (551, NULL, 'Cancel', '删除', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (552, NULL, 'Assign', '赋值', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (553, NULL, 'Join', '连接', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (554, NULL, 'Byte', '字节（二进制的）', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (555, NULL, 'Delimiter', '定界符', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (556, NULL, 'Location', '定位，（存储器）单元', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (557, NULL, 'Sort', '分类，排序', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (558, NULL, 'Sub-Directory', '子目录', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (559, NULL, 'Ascii', '美国信息交换标准码', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (560, NULL, 'Object', '对象，目标', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (561, NULL, 'Coprocessor', '协调处理器', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (562, NULL, 'Keyword', '关键字', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (563, NULL, 'Action', '操作', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (564, NULL, 'Recall', '撤销', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (565, NULL, 'Element', '元件，元素', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (566, NULL, 'Wildcard', '通配符', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (567, NULL, 'Floppy', '软磁盘', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (568, NULL, 'Module', '模块（程序设计）', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (569, NULL, 'Assistance', '辅助设备', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (570, NULL, 'Evaluate', '估算，求值', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (571, NULL, 'Driver', '驱动器', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (572, NULL, 'Linker', '连接程序', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (573, NULL, 'Bios', '输出系统', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (574, NULL, 'Interpreter', '解释程序', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (575, NULL, 'Compatible', '可兼容', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (576, NULL, 'Macros', '宏命令（指令）', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (577, NULL, 'Consist', '符合', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (578, NULL, 'Ask', '请求', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (579, NULL, 'Programming', '程序设计', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (580, NULL, 'Convert', '转换，变换', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (581, NULL, 'Adapter', '适配器', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (582, NULL, 'Receive', '接收', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (583, NULL, 'Listing', '列表', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (584, NULL, 'Ram', '随机存取存储器', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (585, NULL, 'Symbol', '符号', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (586, NULL, 'Binary', '二进制', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (587, NULL, 'Hexadecimal', '十六进制的', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (588, NULL, 'Compression', '压缩', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (589, NULL, 'Emulator', '仿真器，仿真程序', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (590, NULL, 'Compiler', '编译程序', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (591, NULL, 'Converte', '转换的', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (592, NULL, 'Stand', '处于', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (593, NULL, 'Kilobyte', '千字节', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (594, NULL, 'Recognize', '识别', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (595, NULL, 'Terminal', '终端', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (596, NULL, 'Manager', '管理程序', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (597, NULL, 'Answer', '响应', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (598, NULL, 'Handler', '处理程序', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (599, NULL, 'Development', '开发', '刘德威', 'B');
INSERT INTO `proenwords` VALUES (600, NULL, 'Abstract', '抽象的', '徐康', 'B');
INSERT INTO `proenwords` VALUES (601, NULL, 'Abstract Base Class', '抽象基类', '徐康', 'B');
INSERT INTO `proenwords` VALUES (602, NULL, 'Abstract Class', '抽象类', '徐康', 'B');
INSERT INTO `proenwords` VALUES (603, NULL, 'Abstraction', '抽象、抽象物、抽象性', '徐康', 'B');
INSERT INTO `proenwords` VALUES (604, NULL, 'Access', '存取、访问', '徐康', 'B');
INSERT INTO `proenwords` VALUES (605, NULL, 'Access Level', '访问级别', '徐康', 'B');
INSERT INTO `proenwords` VALUES (606, NULL, 'Access Function', '访问函数', '徐康', 'B');
INSERT INTO `proenwords` VALUES (607, NULL, 'Account', '账户', '徐康', 'B');
INSERT INTO `proenwords` VALUES (608, NULL, 'Action', '动作', '徐康', 'B');
INSERT INTO `proenwords` VALUES (609, NULL, 'Activate', '激活', '徐康', 'B');
INSERT INTO `proenwords` VALUES (610, NULL, 'Active', '活动的', '徐康', 'B');
INSERT INTO `proenwords` VALUES (611, NULL, 'Actual Parameter', '实参', '徐康', 'B');
INSERT INTO `proenwords` VALUES (612, NULL, 'Adapter', '适配器', '徐康', 'B');
INSERT INTO `proenwords` VALUES (613, NULL, 'Addin', '插件', '徐康', 'B');
INSERT INTO `proenwords` VALUES (614, NULL, 'Address', '地址', '徐康', 'B');
INSERT INTO `proenwords` VALUES (615, NULL, 'Address Space', '地址空间', '徐康', 'B');
INSERT INTO `proenwords` VALUES (616, NULL, 'Address Of Operator', '取地址操作符', '徐康', 'B');
INSERT INTO `proenwords` VALUES (617, NULL, 'Activex Data Object', 'ActiveX数据对象', '徐康', 'B');
INSERT INTO `proenwords` VALUES (618, NULL, 'Aggregation', '聚合、聚集', '徐康', 'B');
INSERT INTO `proenwords` VALUES (619, NULL, 'Algorithm', '算法', '徐康', 'B');
INSERT INTO `proenwords` VALUES (620, NULL, 'Alias', '别名', '徐康', 'B');
INSERT INTO `proenwords` VALUES (621, NULL, 'Align', '排列、对齐', '徐康', 'B');
INSERT INTO `proenwords` VALUES (622, NULL, 'Allocate', '分配、配置', '徐康', 'B');
INSERT INTO `proenwords` VALUES (623, NULL, 'Allocator', '分配器、配置器', '徐康', 'B');
INSERT INTO `proenwords` VALUES (624, NULL, 'Angle Bracket', '尖括号', '徐康', 'B');
INSERT INTO `proenwords` VALUES (625, NULL, 'Annotation', '注解、评注', '徐康', 'B');
INSERT INTO `proenwords` VALUES (626, NULL, 'Application Domain', '应用域', '徐康', 'B');
INSERT INTO `proenwords` VALUES (627, NULL, 'Application', '应用、应用程序', '徐康', 'B');
INSERT INTO `proenwords` VALUES (628, NULL, 'Application Framework', '应用程序框架', '徐康', 'B');
INSERT INTO `proenwords` VALUES (629, NULL, 'Appearance', '外观', '徐康', 'B');
INSERT INTO `proenwords` VALUES (630, NULL, 'Append', '附加', '徐康', 'B');
INSERT INTO `proenwords` VALUES (631, NULL, 'Architecture', '架构、体系结构', '徐康', 'B');
INSERT INTO `proenwords` VALUES (632, NULL, 'Archive File', '归档文件、存档文件', '徐康', 'B');
INSERT INTO `proenwords` VALUES (633, NULL, 'Argument', '引数', '徐康', 'B');
INSERT INTO `proenwords` VALUES (634, NULL, 'Array', '数组', '徐康', 'B');
INSERT INTO `proenwords` VALUES (635, NULL, 'Arrow Operator', '箭头操作符', '徐康', 'B');
INSERT INTO `proenwords` VALUES (636, 'ASP', 'Active Server Page', '活动服务器页面', '徐康', 'B');
INSERT INTO `proenwords` VALUES (637, NULL, 'Assembly', '装配件、配件', '徐康', 'B');
INSERT INTO `proenwords` VALUES (638, NULL, 'Assembly Language', '汇编语言', '徐康', 'B');
INSERT INTO `proenwords` VALUES (639, NULL, 'Assembly Manifest', '装配件清单', '徐康', 'B');
INSERT INTO `proenwords` VALUES (640, NULL, 'Assert(Ion)', '断言', '徐康', 'B');
INSERT INTO `proenwords` VALUES (641, NULL, 'Assign', '赋值', '徐康', 'B');
INSERT INTO `proenwords` VALUES (642, NULL, 'Assignment', '赋值、分配', '徐康', 'B');
INSERT INTO `proenwords` VALUES (643, NULL, 'Assignment Operator', '赋值操作符', '徐康', 'B');
INSERT INTO `proenwords` VALUES (644, NULL, 'Associated', '相关的、相关联的', '徐康', 'B');
INSERT INTO `proenwords` VALUES (645, NULL, 'Associative Container', '关联式容器', '徐康', 'B');
INSERT INTO `proenwords` VALUES (646, NULL, 'Asynchronous', '异步的', '徐康', 'B');
INSERT INTO `proenwords` VALUES (647, NULL, 'Atomic', '原子的', '徐康', 'B');
INSERT INTO `proenwords` VALUES (648, NULL, 'Atomic Operation', '原子操作', '徐康', 'B');
INSERT INTO `proenwords` VALUES (649, NULL, 'Attribute', '特性、属性', '徐康', 'B');
INSERT INTO `proenwords` VALUES (650, NULL, 'Authentication Service', '验证服务', '徐康', 'B');
INSERT INTO `proenwords` VALUES (651, NULL, 'Authorization', '授权', '徐康', 'B');
INSERT INTO `proenwords` VALUES (652, NULL, 'Audio', '音频', '徐康', 'B');
INSERT INTO `proenwords` VALUES (653, NULL, 'Ai', '人工智能', '徐康', 'B');
INSERT INTO `proenwords` VALUES (654, NULL, 'Business To Business Integration', '整合、B2B集成', '徐康', 'B');
INSERT INTO `proenwords` VALUES (655, NULL, 'Background', '背景', '徐康', 'B');
INSERT INTO `proenwords` VALUES (656, NULL, 'Backward Compatible', '向后兼容、向下兼容', '徐康', 'B');
INSERT INTO `proenwords` VALUES (657, NULL, 'Backup', '备份', '徐康', 'B');
INSERT INTO `proenwords` VALUES (658, NULL, 'Backup Device', '备份设备', '徐康', 'B');
INSERT INTO `proenwords` VALUES (659, NULL, 'Backup File', '备份文件', '徐康', 'B');
INSERT INTO `proenwords` VALUES (660, NULL, 'Bandwidth', '带宽', '徐康', 'B');
INSERT INTO `proenwords` VALUES (661, NULL, 'Base Class', '基类', '徐康', 'B');
INSERT INTO `proenwords` VALUES (662, NULL, 'Base Type', ' 基类型', '徐康', 'B');
INSERT INTO `proenwords` VALUES (663, NULL, 'Batch', '批处理', '徐康', 'B');
INSERT INTO `proenwords` VALUES (664, 'BCL', 'Base Class Library', '基类库', '徐康', 'B');
INSERT INTO `proenwords` VALUES (665, NULL, 'Binary', '二进制', '徐康', 'B');
INSERT INTO `proenwords` VALUES (666, NULL, 'Binary Search', '二分查找', '徐康', 'B');
INSERT INTO `proenwords` VALUES (667, NULL, 'Binary Tree', '二叉树', '徐康', 'B');
INSERT INTO `proenwords` VALUES (668, NULL, 'Binary Function', '双参函数', '徐康', 'B');
INSERT INTO `proenwords` VALUES (669, NULL, 'Binary Large Object', '二进制大对象', '徐康', 'B');
INSERT INTO `proenwords` VALUES (670, NULL, 'Binary Operator', '二元操作符', '徐康', 'B');
INSERT INTO `proenwords` VALUES (671, NULL, 'Binding', '绑定', '徐康', 'B');
INSERT INTO `proenwords` VALUES (672, NULL, 'Bit', '位', '徐康', 'B');
INSERT INTO `proenwords` VALUES (673, NULL, 'Bitmap', '位图', '徐康', 'B');
INSERT INTO `proenwords` VALUES (674, NULL, 'Bitwise', '按位', '徐康', 'B');
INSERT INTO `proenwords` VALUES (675, NULL, 'Bitwise Copy', '为单元进行复制；位元逐一复制,按位拷', '徐康', 'B');
INSERT INTO `proenwords` VALUES (676, NULL, 'Bitwise Operation', '按位运算', '徐康', 'B');
INSERT INTO `proenwords` VALUES (677, NULL, 'Block', '块、区块、语句块', '徐康', 'B');
INSERT INTO `proenwords` VALUES (678, NULL, 'Bookkeeping', '簿记', '徐康', 'B');
INSERT INTO `proenwords` VALUES (679, NULL, 'Boolean', '布尔值', '徐康', 'B');
INSERT INTO `proenwords` VALUES (680, NULL, 'Border', '边框', '徐康', 'B');
INSERT INTO `proenwords` VALUES (681, NULL, 'Bounds Checking', '边界检查', '徐康', 'B');
INSERT INTO `proenwords` VALUES (682, NULL, 'Boxing', '装箱、装箱转换', '徐康', 'B');
INSERT INTO `proenwords` VALUES (683, NULL, 'Curly Brace', '花括号', '徐康', 'B');
INSERT INTO `proenwords` VALUES (684, NULL, 'Square Brakcet', '方括号', '徐康', 'B');
INSERT INTO `proenwords` VALUES (685, NULL, 'To Read', '读取', '徐康', 'B');
INSERT INTO `proenwords` VALUES (686, NULL, 'Breakpoint', '断点', '徐康', 'B');
INSERT INTO `proenwords` VALUES (687, NULL, 'Browser Applications', '浏览器应用(程序)', '徐康', 'B');
INSERT INTO `proenwords` VALUES (688, NULL, 'Browser Accessible Application', '可经由浏览器访问的应用程序', '徐康', 'B');
INSERT INTO `proenwords` VALUES (689, NULL, 'Build', '编连(专指编译和连接', '徐康', 'B');
INSERT INTO `proenwords` VALUES (690, NULL, 'Built In', '内建、内置', '徐康', 'B');
INSERT INTO `proenwords` VALUES (691, NULL, 'Bus', '总线', '徐康', 'B');
INSERT INTO `proenwords` VALUES (692, NULL, 'Business', '业务、商务', '徐康', 'B');
INSERT INTO `proenwords` VALUES (693, NULL, 'Business Logic', '业务逻辑', '徐康', 'B');
INSERT INTO `proenwords` VALUES (694, NULL, 'Business Rules', '业务规则', '徐康', 'B');
INSERT INTO `proenwords` VALUES (695, NULL, 'Wrapper', '包装器', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (696, NULL, 'Word', '单词', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (697, NULL, 'Window', '窗口', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (698, NULL, 'Wildcard', '通配符', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (699, NULL, 'Weight', '权值', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (700, NULL, 'Vowel', '元音', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (701, NULL, 'Volatile', '挥发', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (702, NULL, 'View', '视图', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (703, NULL, 'Video', '视频', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (704, NULL, 'Vector', '向量', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (705, NULL, 'Variant', '变种', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (706, NULL, 'Variable', '变量', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (707, NULL, 'Validator', '验证器', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (708, NULL, 'Validate', '验证', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (709, NULL, 'Utilities', '实用函数', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (710, NULL, 'User', '用户', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (711, NULL, 'Uptime', '运行时间', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (712, NULL, 'Unqualfied', '未修饰的', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (713, NULL, 'Union', '并集', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (714, NULL, 'Unification', '合一', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (715, NULL, 'Underflow', '下溢', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (716, NULL, 'Unary', '一元的', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (717, NULL, 'Typing', '类型指派', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (718, NULL, 'Type variable', '类型变量', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (719, NULL, 'Type synonym', '类型别名', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (720, NULL, 'Type signature', '类型签名', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (721, NULL, 'Type safe', '类型安全', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (722, NULL, 'Type name', '类型名', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (723, NULL, 'Type inference', '类型推导', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (724, NULL, 'Type hierarchy', '类型层级', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (725, NULL, 'Type declaration', '类型声明', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (726, NULL, 'Type constructor', '类型造器', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (727, NULL, 'Type', '类型', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (728, NULL, 'Typable', '类型合法', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (729, NULL, 'Tuple', '元组', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (730, NULL, 'Trigger', '触发器', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (731, NULL, 'Tree', '树', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (732, NULL, 'Traverse', '透明的', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (733, NULL, 'Transition network', '转移网络', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (734, NULL, 'Transaction', '事务', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (735, NULL, 'Trailing', '行尾空白', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (736, NULL, 'Trace', '追踪', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (737, NULL, 'Top-level', '顶层', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (738, NULL, 'Token', '词法记号', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (739, NULL, 'Timestamp', '时间戳', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (740, NULL, 'Throwaway program', '一次性程序', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (741, NULL, 'Throw', '抛出', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (742, NULL, 'Three-valued logic', '三值逻辑', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (743, NULL, 'Thread safe', '线程安全', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (744, NULL, 'Thread', '线程', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (745, NULL, 'Text file', '文本文件', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (746, NULL, 'Text', '文本', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (747, NULL, 'Testing', '测试', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (748, NULL, 'Template', '模版', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (749, NULL, 'Taxonomy', '分类法', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (750, NULL, 'Target', '目标', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (751, NULL, 'Tag', '标签', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (752, NULL, 'Table', '表格', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (753, NULL, 'Database Table', '数据表', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (754, NULL, 'Syntax', '语法', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (755, NULL, 'Symbol', '符号', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (756, NULL, 'Swapping values', '交换变量的值', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (757, NULL, 'Suspend', '挂起', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (758, NULL, 'Support', '支持', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (759, NULL, 'Supertype', '超集', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (760, NULL, 'Superfluous', '多余的', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (761, NULL, 'Superclass', '基类', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (762, NULL, 'Subtype', '子类型', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (763, NULL, 'Substitution model', '代换模型', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (764, NULL, 'Substitution', '代换', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (765, NULL, 'Subset', '子集', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (766, NULL, 'Subroutine', '子程序', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (767, NULL, 'Structural recursion', '结构递归', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (768, NULL, 'Structured values', '结构型值', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (769, NULL, 'Strong type', '强类型', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (770, NULL, 'String', '字串', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (771, NULL, 'Strict', '严格', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (772, NULL, 'Stream', '流', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (773, NULL, 'Store', '保存', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (774, NULL, 'Status', '状态', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (775, NULL, 'Static type', '静态类型', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (776, NULL, 'Statement', '陈述', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (777, NULL, 'State machine', '状态机', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (778, NULL, 'Standard library', '标准函式库', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (779, NULL, 'Stack frame', '栈帧', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (780, NULL, 'Stack', '栈', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (781, NULL, 'Squash', '碰撞', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (782, NULL, 'Square root', '平方根', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (783, NULL, 'Square', '平方', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (784, NULL, 'Splitter', '切分窗口', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (785, NULL, 'Software', '软件', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (786, NULL, 'Solution', '方案', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (787, NULL, 'Source code', '源代码', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (788, NULL, 'Spec', '规格', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (789, NULL, 'Specialize', '特化', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (790, NULL, 'Sequential', '序列', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (791, NULL, 'Semicolon', '分号', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (792, NULL, 'Semaphore', '信息量', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (793, NULL, 'Semantics', '语义', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (794, NULL, 'Search', '查找', '廖宇豪', 'B');
INSERT INTO `proenwords` VALUES (795, NULL, 'Command', '命令, 指令', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (796, NULL, 'File', '文件, 保存文件', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (797, NULL, 'Use', '使用, 用途', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (798, NULL, 'Program', '程序', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (799, NULL, 'Line', '行, 线路', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (800, NULL, 'If', '如果', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (801, NULL, 'Display', '显示, 显示器', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (802, NULL, 'Set', '设置, 集合', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (803, NULL, 'Key', '键，关键字，关键码', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (804, NULL, 'List', '列表', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (805, NULL, 'By', '凭，靠，', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (806, NULL, 'Press', '按，压', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (807, NULL, 'With', '用，与，随着', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (808, NULL, 'Format', '格式', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (809, NULL, 'Change', '更换，改变，变动', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (810, NULL, 'Cursor', '光标', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (811, NULL, 'Directory', '目录，索引簿', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (812, NULL, 'From', '从，来自，以来', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (813, NULL, 'Menu', '菜单，目录', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (814, NULL, 'Option', '任选，选择，可选项', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (815, NULL, 'Character', '字符，符号，特性', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (816, NULL, 'Current', '电流', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (817, NULL, 'Type', '型，类型；打印', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (818, NULL, 'Screen', '屏幕，屏；屏蔽', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (819, NULL, 'Specify', '指定，规定，确定', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (820, NULL, 'Move', '移动', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (821, NULL, 'Disk', '盘，磁盘', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (822, NULL, 'Text', '正文，文本', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (823, NULL, 'Drive', '驱动；驱动器', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (824, NULL, 'See', '看出，查看', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (825, NULL, 'Name', '名，名称，命名', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (826, NULL, 'Record', '记录', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (827, NULL, 'Box', '箱，匣，(逻辑)框', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (828, NULL, 'Database', '数据库', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (829, NULL, 'Help', '帮助', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (830, NULL, 'Memory', '记忆存储，存储器', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (831, NULL, 'Which', '哪个，那一个', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (832, NULL, 'All', '全，全部；', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (833, NULL, 'On', '接通，导电，开', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (834, NULL, 'Copy', '复制，拷贝', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (835, NULL, 'Shell', '壳，外壳', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (836, NULL, 'Delete', '删除，删去，作废', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (837, NULL, 'Enter', '键入，送入', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (838, NULL, 'Margin', '余量，边缘，边际', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (839, NULL, 'Mark', '标记', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (840, NULL, 'Also', '也，亦，还', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (841, NULL, 'Do', '做，干；循环', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (842, NULL, 'Information', '信息，情报', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (843, NULL, 'Choose', '挑选，选择，选定', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (844, NULL, 'Select', '选择', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (845, NULL, 'Just', '恰好', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (846, NULL, 'Undo', '取消', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (847, NULL, 'Environ', '围绕', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (848, NULL, 'Why', '为什么', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (849, NULL, 'Temporary', '暂时的', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (850, NULL, 'Put', '放置', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (851, NULL, 'Instead', '代替', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (852, NULL, 'Encounter', '遇到', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (853, NULL, 'Across', '交叉', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (854, NULL, 'Matching', '匹配', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (855, NULL, 'Wildcard', '通配符', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (856, NULL, 'Spill', '漏出', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (857, NULL, 'Level', '水平', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (858, NULL, 'Browse', '浏览', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (859, NULL, 'Speech', '说话', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (860, NULL, 'Occur', '发生', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (861, NULL, 'Memo', '备忘录', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (862, NULL, 'Prior', '优先的', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (863, NULL, 'Loaded', '有负载的', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (864, NULL, 'Length', '长度', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (865, NULL, 'Round', '舍入', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (866, NULL, 'Variant', '变体', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (867, NULL, 'Floppy', '软磁盘', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (868, NULL, 'Machine', '机器', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (869, NULL, 'Square', '正方形', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (870, NULL, 'Supply', '电源', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (871, NULL, 'Home', '家', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (872, NULL, 'Normal', '正常', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (873, NULL, 'Onto', '向什么', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (874, NULL, 'During', '在什么期间', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (875, NULL, 'Module', '模块', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (876, NULL, 'Monochrome', '单色', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (877, NULL, 'Assistance', '帮助', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (878, NULL, 'Tell', '讲', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (879, NULL, 'Library', '图书馆', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (880, NULL, 'Demonstration', '师示范', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (881, NULL, 'Stack', '存储栈', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (882, NULL, 'Even', '偶数', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (883, NULL, 'Evaluate', '估算', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (884, NULL, 'Times', '次数', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (885, NULL, 'Previously', '以前', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (886, NULL, 'Directly', '直接地', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (887, NULL, 'Logical', '逻辑的', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (888, NULL, 'Template', '模板', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (889, NULL, 'Calling', '调用', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (890, NULL, 'Later', '更后的', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (891, NULL, 'Driver', '驱动器', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (892, NULL, 'Therefore', '因此', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (893, NULL, 'Saving', '保存的', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (894, NULL, 'Detail', '元件', '陈浩民', 'B');
INSERT INTO `proenwords` VALUES (895, NULL, 'Library', '库，程序库', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (896, NULL, 'Batch Processing', '成批处理', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (897, NULL, 'Binary Wxxxcode-Style', '二进制码', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (898, NULL, 'Binary Digit', '二进制位，二进制数字', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (899, NULL, 'Bit', '比特，二进制的一位', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (900, NULL, 'Branch', '分支，支线', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (901, NULL, 'Buffer Storage', '缓冲存储器', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (902, NULL, 'Calculator', '计算器', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (903, NULL, 'Call Instruction', '呼叫指令', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (904, NULL, 'Card Punch', '卡片穿孔机', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (905, NULL, 'Card Reader', '卡片阅读机，读卡机', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (906, NULL, 'Cell', '单元', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (907, NULL, 'Channel', '通道，信道', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (908, NULL, 'Character', '字符', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (909, NULL, 'Check Digit', '校验数位', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (910, NULL, 'Circuit', '电路，线路', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (911, NULL, 'To Clear', '清除，清零', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (912, NULL, 'Clock', '时钟', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (913, NULL, 'Wxxxcode-Style', '代码', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (914, NULL, 'To Wxxxcode-Style', '编码', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (915, NULL, 'Wxxxcode-Styler', '编码员，编码器', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (916, NULL, 'Command', '指令，命令', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (917, NULL, 'Compiler', '编译程序', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (918, NULL, 'Computer Language', '计算机语言', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (919, NULL, 'Console', '控制台', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (920, NULL, 'Control Unit', '控制部件，控制器', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (921, NULL, 'Core Storage', '磁心存储器', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (922, NULL, 'Counter', '计数器', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (923, NULL, 'Cybernetics', '控制论', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (924, NULL, 'Cycle', '循环', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (925, NULL, 'Data', '数据', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (926, NULL, 'Data Processing', '数据处理', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (927, NULL, 'Debugging', '调试', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (928, NULL, 'Decision', '制定', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (929, NULL, 'Digit', '数位，位', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (930, NULL, 'Digital Computer', '数字计算机', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (931, NULL, 'Disc Disk', '磁盘', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (932, NULL, 'Display Unit', '显示装置', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (933, NULL, 'Drum', '磁鼓', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (934, NULL, 'To Edit', '编辑', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (935, NULL, 'Electronics', '电子学', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (936, NULL, 'Emitter', '发射器', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (937, NULL, 'To Erase', '擦除，清洗，抹除', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (938, NULL, 'Casefeed', '馈送，供给', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (939, NULL, 'To Feed', '馈送，供给', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (940, NULL, 'Feedback', '反馈', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (941, NULL, 'Field', '字段，信息组，域', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (942, NULL, 'File', '文件', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (943, NULL, 'Floppy Disk', '软磁盘', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (944, NULL, 'Floppy Disk Drive', '软磁盘机', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (945, NULL, 'Flow Chart', '流程图', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (946, NULL, 'Frame', '帧', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (947, NULL, 'Hardware', '硬件', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (948, NULL, 'Identifier', '标识符', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (949, NULL, 'Index', '索引', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (950, NULL, 'Information', '信息', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (951, NULL, 'Inline Processing', '内处理', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (952, NULL, 'Input', '输入', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (953, NULL, 'Inquiry', '询问', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (954, NULL, 'Instruction', '指令', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (955, NULL, 'Integrated Circuit', '集成电路', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (956, NULL, 'To Interpret', '解释', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (957, NULL, 'Item', '项目，项', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (958, NULL, 'Jump', '转移', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (959, NULL, 'Key', '键，关键码', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (960, NULL, 'Loss', '损耗，损失', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (961, NULL, 'Batch', '批，批量，成批', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (962, NULL, 'Exact', '正确的', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (963, NULL, 'Aboveboard', '照直，公开的', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (964, NULL, 'Activate', '使激活，驱动', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (965, NULL, 'Around', '周围，围绕', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (966, NULL, 'Slow', '慢速的', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (967, NULL, 'Floating', '浮动的，浮点的', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (968, NULL, 'Refresh', '刷新，更新，再生', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (969, NULL, 'Stop', '停止，停机', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (970, NULL, 'Pass', '传送，传递，遍', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (971, NULL, 'Public', '公用的，公共的', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (972, NULL, 'Eject', '弹出', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (973, NULL, 'Ignore', '不管，忽略不计', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (974, NULL, 'Share', '共享，共用', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (975, NULL, 'Sequence', '顺序，时序，序列', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (976, NULL, 'Consist', '符合，包括', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (977, NULL, 'Step', '步，步骤，步长，档', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (978, NULL, 'Double', '两倍的，成双的', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (979, NULL, 'Come', '来，到，出现', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (980, NULL, 'Lower', '下部的，低级的', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (981, NULL, 'Count', '计数，计算', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (982, NULL, 'Valid', '有效的', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (983, NULL, 'Enhance', '增强，放大，夸张', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (984, NULL, 'Separate', '分隔，分离，各自', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (985, NULL, 'Echo', '回波，反射波', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (986, NULL, 'Necessary', '必要的，必然的', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (987, NULL, 'Greater Than', '大于', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (988, NULL, 'Able', '能', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (989, NULL, 'Marking', '标记，记号，传号', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (990, NULL, 'Ask', '请求，需要', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (991, NULL, 'Term', '项，条款，术语', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (992, NULL, 'Bring', '引起，产生，拿来', '邱思曼', 'B');
INSERT INTO `proenwords` VALUES (993, NULL, 'Warning', '报警，预告', '邱思曼', 'B');

-- ----------------------------
-- Table structure for ranklist
-- ----------------------------
DROP TABLE IF EXISTS `ranklist`;
CREATE TABLE `ranklist`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `clas` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `name` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `level` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `score` int(40) NOT NULL,
  `date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of ranklist
-- ----------------------------

SET FOREIGN_KEY_CHECKS = 1;
